language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
install: echo "Installing"
jobs:
  include:
    - stage: test
      script: npm install && cd server && npm install && cd .. && npm run test
      on:
        branch: develop
stages:
  - name: test
    if: (branch = develop)
