language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
notifications:
  email: false
install: echo "install happens as part of setup"
script: npm install
branches:
  only:
  - master
