language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
install: echo "Installing"
jobs:
  include:
    - stage: test
      script: npm install && npm run test
      on:
        branch: develop
    - stage: deploy
      script: npm install && npm build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_API_KEY
        keep-history: true
      on:
        branch: master
stages:
  - name: test
    if: (branch = develop)
  - name: deploy
    if: (branch = master)
