language: node_js
node_js:
  - 'lts/*'

services:
  - postgresql

cache:
  directories:
    - ~/.npm
    - ~/.cache

before_install:
  - psql -c 'create database rockstagramdev;' -U postgres

script:
  - npm install && cd server && npm install && cd .. && npm test
