language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
install: echo "Installing"
script: npm install
jobs:
  include:
    - stage: test
      script: npm run test
      on:
        branch: develop
    - stage: deploy
      script: npm run deploy
      on:
        branch: master
